### ISSUE TITLE
The options of size, concs, and shape does'n write out properly.

### ISSUE THREAD

**Issue by wsmorgan** [wsmorgan/phonon-enumeration#14]
```
Traceback (most recent call last):
  File "/Users/wileymorgan/.virtualenvs/fortpy-dev/bin/enumeration.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/wileymorgan/Documents/research/enum4/phonon-enumeration/phenum/enumeration.py", line 331, in <module>
    script_enum(_parser_options())
  File "/Users/wileymorgan/Documents/research/enum4/phonon-enumeration/phenum/enumeration.py", line 328, in script_enum
    _enum_in(args)
  File "/Users/wileymorgan/Documents/research/enum4/phonon-enumeration/phenum/enumeration.py", line 18, in _enum_in
    make_enum_in(distribution,dataformat=args["dataformat"])
  File "/Users/wileymorgan/Documents/research/enum4/phonon-enumeration/phenum/structures.py", line 576, in make_enum_in
    _print_distribution(distr,filename="enum.in")
  File "/Users/wileymorgan/Documents/research/enum4/phonon-enumeration/phenum/structures.py", line 544, in _print_distribution
    f.write("  {0: <28}  {1: <10}  {2:d}\n".format(' '.join(map(str, HNF)), ' '.join(map(str, conc)), value))
TypeError: argument 2 to map() must support iteration
```

**Comment by wsmorgan** [comment]
Fixed in Revision 1.6.0
