### ISSUE TITLE
Error for some basis vectors for generating the space group.

### ISSUE THREAD

**Issue by wsmorgan** [wsmorgan/phonon-enumeration#15]
Input:

```
# Which cell-sizes do you want to search?
4 4
#---------------------------------------
# Bulk or surface?
bulk
# List the primitive cell's lattice vectors
 0.5 0.5 0.0
 0.0 0.5 0.5
 0.5 0.0 0.5
# number of atomic species in the cell
3
# basis atoms
3
0 0 0
0.25 0.25 0.75
0.5 0.5 0.25
#----------------------------------------
# Concentrations
#
# - use specific concentration range (T/F)
# - use arrows on some of the atoms (T/F)
# The concentration ranges for each atom are specified by three
# integers, which define 2 fractions. The third number is the
# denominator for the fraction, the first two numbers are the
# numerator. The first two numbers need not be listed in ascending
# order.
#
# If displacement directions are to be used then a fourth number
# follows the fractions the fourth number should be a decimal that
# indicates the fractional amount of displaced atoms of that species.
T
T
0 4 4 0.0
0 4 4 0.0
```

Output error:

```
Traceback (most recent call last):
  File "/Users/wileymorgan/.virtualenvs/fortpy-dev/bin/enumeration.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/wileymorgan/Documents/research/enum4/phonon-enumeration/phenum/enumeration.py", line 336, in <module>
    _script_enum(_parser_options())
  File "/Users/wileymorgan/Documents/research/enum4/phonon-enumeration/phenum/enumeration.py", line 329, in _script_enum
    _polya_out(args)
  File "/Users/wileymorgan/Documents/research/enum4/phonon-enumeration/phenum/enumeration.py", line 63, in _polya_out
    sym_g = get_sym_group(params["lat_vecs"],params["basis_vecs"],get_full_HNF(HNF),3)
  File "/Users/wileymorgan/Documents/research/enum4/phonon-enumeration/phenum/grouptheory.py", line 660, in get_sym_group
    sgshifts,ParRPList,eps)
  File "/Users/wileymorgan/Documents/research/enum4/phonon-enumeration/phenum/grouptheory.py", line 156, in _get_sLV_fixing_operations
    tv.append(dPerm.v[iRot])
IndexError: list index out of rangeiu
```

The problem seems to be that _get_dvector_permutations returns null vectors and that the space group found inside _get_dvector_permutations returns: `out =  ([], [])`.

**Comment by wsmorgan** [comment]
Fixed in revision 1.5.7.
