### ISSUE TITLE
Python 3 integer division issues in SmithNormalForm

### ISSUE THREAD

**Issue by wsmorgan** [wsmorgan/phonon-enumeration#61]
```
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from phenum.grouptheory import SmithNormalForm
>>> H = [[41,0,0],[0,21,0],[0,0,41]]
>>> SmithNormalForm(H)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wileymorgan/codes/phonon-enumeration/phenum/grouptheory.py", line 304, in SmithNormalForm
    raise RuntimeError("Bad programming in SmithNormalForm")
RuntimeError: Bad programming in SmithNormalForm
```

**Comment by wsmorgan** [comment]
The problem was on line 333 of grouptheory.py. The line:
```
mult = M[j][maxidx]/M[j][minidx]
```
has been replaced with:
```
mult = M[j][maxidx]//M[j][minidx]
```
Fixed in revision 2.0.6.
