### ISSUE TITLE
Examples for creating unique displacement configurations

### ISSUE THREAD

**Issue by nhew1994** [wsmorgan/phonon-enumeration#80]
Hi, this is Nigel Hew. I am a postdoc for Penn State. Do you have any examples I can try to enumerate unique displacement configurations?

**Comment by wsmorgan** [comment]
There is a sample fcc cell in the `inputs` directory. If that's not what your after then I may be able to come up with one if you can be more specific about your needs.

**Comment by nhew1994** [comment]
Thanks @wsmorgan. I will try that and get back to you.

**Comment by nhew1994** [comment]
Hi @wsmorgan. I've been trying out some examples as specified in the README. It seems that:

- makeStr.py has to be replaced by phenumStr.py in the README
- phenumStr.py expects a struct_enum.out file, but if you do `enumeration.py -enum` it creates a file named enum.out instead.
- After running `enumeration.py -visualize -shape`, I get the following error 

Concentrations are being restricted.
Traceback (most recent call last):
  File "/jet/home/nhew/.conda/envs/dfttk/bin/enumeration.py", line 399, in <module>
    _script_enum(args)
  File "/jet/home/nhew/.conda/envs/dfttk/bin/enumeration.py", line 390, in _script_enum
    _plot_HNFs(args,testmode=testmode)
  File "/jet/home/nhew/.conda/envs/dfttk/bin/enumeration.py", line 14, in _plot_HNFs
    HNF_shapes(args["input"],args["lattice"],args["show"],testmode=testmode)
  File "/jet/home/nhew/.conda/envs/dfttk/lib/python3.12/site-packages/phenum/visualize.py", line 37, in HNF_shapes
    with open(enum,"r") as inf:
         ^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType

Regards,
Nigel
